### ISSUE TITLE
input not plotted correctly

### ISSUE THREAD

**Issue by hn-88** [pyNLO/PyNLO#33]
Just to check @DanHickstein 's comment that 'steps' is only used in plotting, I tried changing the Steps=50 to Steps=3 in the example at http://pynlo.readthedocs.io/en/latest/example_simple.html

It worked fine. Only issue was that the input pulse was not graphed correctly (in blue, in the top two graphs). My first thought was that instead of zW[0], zW[1] is being graphed. But in the code, it is zW[0]

![scg3](https://cloud.githubusercontent.com/assets/6321069/15173196/68759204-1778-11e6-813c-db2e0ceecab1.jpg)

Not sure how important this is. Probably can be ignored?

**Comment by DanHickstein** [comment]
This is an important observation - I had actually assumed that the first element (well, first column I suppose, since it gets transposed on it's way to becoming the zW array in that example) in the ZW array was indeed the pulse before any propagation. In my simulations, very little changes during the first step, so I had never realized that it was different that the original pulse. You can always access the 1D array corresponding to the intensity of the original pulse using `pulse.AW`.

I think that the argument could be made that AW should not include the first step, since it only includes the results _after_ propagation. Personally, I think that it would be more intuitive if it did include the field at y=0. As it stands, there is currently an inconsistency in that the returned `z_positions` array contains `(n_steps + 1)` elements, while the size of `AW` and `AT` is `(pulse_in.NPTS, n_steps)`. (I'm looking around[ Line 511 of SSFM.py](https://github.com/pyNLO/PyNLO/blob/master/src/pynlo/interactions/FourWaveMixing/SSFM.py#L511))

@ycasg, what do you think? Should we include the pulse before propagation as the first element of `AW` and `AT` returned by `SSFM.propagate`? Or, should be drop the first element of z_positions?

**Comment by ycasg** [comment]
I had been happy with the way this was working, as the pulse_in and pulse_out objects can access the field at the endpoints. However, I just pulled my copy of Numerical Recipes off the shelf and looked at the ODE integrator algorithm that they implement. Not only is this ia pretty good reference for numerical algorithms, but it is what I use in the pyNLO Dopri integrator.

In it, the output grid does in fact start at x1 and end at x2, with a total of N+1 points; the +1 is the initial value. I think that we should change the SSFM output grid to this standard.

**Comment by DanHickstein** [comment]
Sounds good, I think that is intuitively what @hn-88 and I expected would happen, so it must be the right thing to do :)

**Comment by DanHickstein** [comment]
Let's keep this issue open to remind us to make the change.
